### ISSUE TITLE
Installing with pip according to instructions does not work

### ISSUE THREAD

**Issue by geloescht** [theochem/procrustes#116]
This is on Python 3.9. pip install qc-procrustes results in this error:
```
ERROR: Could not find a version that satisfies the requirement qc-procrustes (from versions: none)
ERROR: No matching distribution found for qc-procrustes
```

**Comment by fwmeng88** [comment]
Thank you for your interest in our package. 

We haven't released `procrustes` to PyPI yet, but you can install it with
```bash
# download package with git or manually download the ZIP  file
git clone git@github.com:theochem/procrustes.git
#  install package with pip
cd procrustes
pip install .
```

Please let me know if it does not work. @geloescht

**Comment by fwmeng88** [comment]
I am going to close this issue for now. But feel free to reopen if you still have problems with package installation and I would be very happy to help.

**Comment by geloescht** [comment]
I can confirm that this works. It does install a number of dependencies that seem unnecessary for a production environment (sphinx, pytest), but that might have something to do with installing from a local directory rather than PyPI.
I hope Procrustes will be released soon! The methods in more common libraries such as SciPy are seriously lacking. Keep up the good work!

**Comment by fwmeng88** [comment]
Thanks for the nice words!!

**Comment by FarnazH** [comment]
Thanks for your interest @geloescht. Just to let you know, we have released a `dev` version of `procrustes` on conda and pypi (see the updated installation instructions). We will release a `main` release in the coming days.
