### ISSUE TITLE
Would be nice to have the used scaling and translation returned in the answer

### ISSUE THREAD

**Issue by esoinila** [theochem/procrustes#166]
Now the scaling factor and translation vector are calculated in the utilities but they are not returned in the answer (result = orthogonal(a, b, scale=True, translate=True)). For 3D-graphics calculations, these would be handy to scale and translate any new points found from the distance matrix (I get preliminary coordinates from MDS) back into the real coordinates of b.

**Comment by fwmeng88** [comment]
Thank you for your interest in our work!

To get the scaling factor, you can call the function `_scale_array` after importing,
```python
from procrustes.utils import _scale_array
```
And the scaling factor can be accessed as the second element of the returned tuple. More details 
https://github.com/theochem/procrustes/blob/8454b837fbf0ce1cf695b736b5e145108849ef32/procrustes/utils.py#L158-184. 

For translation matrix, it's almost the same.
```python
from procrustes.utils import _translate_array
```

For changing the return to include these two elements, is this a often case in your field? We may discuss within our team and then get it back to you.
@esoinila

**Comment by esoinila** [comment]
Thanks for the quick reply. I will test those methods on Monday.
 
My use case is the case where I want to add new datapoints into 3D word without changing the original 3D world coordinates. Suppose in-door navigation with something like bluetooth signal strength giving approximate distances to devices as distance matrix. For some beacons we know their positions beforehand (we have placed them into space intentionally into known locations as beacons). Ideally we want to use these known positions to calculate a transition for putting the new distance matrix points on the 3D-map into correct position(s) (a new point could be your phone with bluetooth on).  

The only difference to now would be that is that instead of comparing points from distance matrix to known point positions would happen in correct world coordinates instead of the scaled/translated ones (see image). One way to accomplish this robustly would be to get used scale and translation so these changes can be reversed (this is my current approach). Even fancier option would be to have an option to use b-matrix scale in results.
 
![image](https://user-images.githubusercontent.com/70575390/162609231-4ca8936d-c423-446d-b5ee-8aa220601d86.png)

**Comment by PaulWAyers** [comment]
@fwmeng88 and @FarnazH: we should think about whether we want to return the scale/translate or support it only as @fwmeng88 mentions. It is a substantial revision (albeit an easy one) to adjust all the returns.

I don't have a strong feeling for pros vs. cons. If we were doing it all over again, I guess that returning the translation/scaling automatically might have been sensible. The con I see is only that it makes the return a lot more complicated, and the scaling/translation is not always done (it's an option) and so we want to return `None` that frequently? 

It may be that a documentation fix is more appropriate, then. Y'all's thoughts? We might at least not make these methods "hidden/internal" methods.

**Comment by fwmeng88** [comment]
No problem at all. 

Yes, these are private functions, but it's great that it's useful for you. Please let me know if you have further questions. @esoinila

**Comment by fwmeng88** [comment]
I thought about this again and maybe we don't need to have a return of scaling factor or translation matrix as in most cases, this makes too many returns. I would favor clear documentation, somewhere like https://procrustes.qcdevs.org/notebooks/Quick_Start.html? @PaulWAyers @FarnazH

**Comment by PaulWAyers** [comment]
Just to be clear, this is in the `quickstart.ipynb` Jupyter notebook. 

@FanwangM I made a few tweaks to verbiage, which are hopefully OK.

**Comment by FanwangM** [comment]
Thank you. I will take a look soon. @PaulWAyers
