### ISSUE TITLE
transform_mode for permutation_2sided is different than documented

### ISSUE THREAD

**Issue by wilhadams** [theochem/procrustes#23]
In [the docs](https://procrustes.readthedocs.io/en/latest/api/permutation.html#procrustes.permutation.permutation_2sided), the `transform_mode` argument for `permutation_2sided` should be one of `single_undirected`, `single_directed`, `double`. In [the code](https://github.com/theochem/procrustes/blob/master/procrustes/permutation.py#L412), it can only be `single` or `double`, and then the directed/undirected mode is chosen based on testing the suitability of the matrix.

**Comment by fwmeng88** [comment]
Thanks for pointing it out. @wilhadams 

I have updated the docsrings in PR #36.

**Comment by fwmeng88** [comment]
This issue is fixed in PR #36 and I am going to close this.
