### ISSUE TITLE
Finalize ProcrustesResult argument names & default values

### ISSUE THREAD

**Issue by FarnazH** [theochem/procrustes#25]
For example, instead of `e_opt`, I think `error` would be a more intuitive argument.
See: https://github.com/theochem/procrustes/blob/master/procrustes/utils.py#L562

**Comment by fwmeng88** [comment]
This is a very nice point!

We also have an `error()` function in https://github.com/theochem/procrustes/blob/ab607f1209c38de2b23a9268378146afc616bf44/procrustes/utils.py#L236-L275.

To avoid ambiguity, can we name `e_opt` as `distance`? Or we can rename `error()` function as `compute_error()`. 
@FarnazH  Thanks.
