### ISSUE TITLE
Tutorial Examples

### ISSUE THREAD

**Issue by FarnazH** [theochem/procrustes#26]
Turn the code blocks given in tutorials into Python scripts (and then reference them in the documentation), so it can be easily downloaded and executed. It is also important to check that they run properly as the code changes.

Example: http://theochem.github.io/horton/2.1.1/user_postproc_aim.html#python-interface-to-the-partitioning-code

**Comment by FarnazH** [comment]
@fwmeng88 what is the status of this issue? I think the last time we talked, we decided to turn the code snippets in the paper into example notebooks (so that it can be easily run by the reviewers) alongside the updated imaeges.

**Comment by FarnazH** [comment]
@fwmeng88 I don't think we need both tutorials and notebooks. We need to harmonize tutorial code snippets & figures with the paper. I would focus on polishing the notebooks, and then display them on the website or add a link to GitHub. Let me know your thoughts.

**Comment by fwmeng88** [comment]
This is a good point! I will try to remove the `.py` files in examples and keep only jupyter notebooks. Will push them to GitHub later today. 

Thanks! @FarnazH

**Comment by fwmeng88** [comment]
Updates: For now, I am planning to only keep the notebooks and remove the `examples` folder. Refactorization of notebooks have been addressed in PR #87, #88, #89, #90. Any suggestion or comment is welcome.

@FarnazH

**Comment by FarnazH** [comment]
@fwmeng88 I think it's best to add the quick start as a notebook too.

**Comment by fwmeng88** [comment]
Good point! I will add one soon.

**Comment by fwmeng88** [comment]
For now, we will need to delete all the files in **examples** folder and update all the *RST* files to make it consistent with all the jupyter notebooks.

**Comment by fwmeng88** [comment]
This issue is addressed in #106 as we use `nbsphinx` to host all the notebooks.
