### ISSUE TITLE
Change argument names

### ISSUE THREAD

**Issue by FarnazH** [theochem/procrustes#30]
I remember that at some point we talked about changing the argument names to `array_a` and `array_b` to `a` and `b`. I still think it is good to be consistent with `numpy` and `scipy` and use shorter argument names.
See: https://github.com/theochem/procrustes/blob/master/procrustes/orthogonal.py#L37
What do you think @PaulWAyers?

**Comment by PaulWAyers** [comment]
I think we agreed this was a good thing to do. We should use "generic" one-letter names for input arguments. Probably the transformation matrix (matrices) should have generic one-character names that makes it clear if they are right-hand or left-hand transformations too (in cases where they are equal one argument could be set equal to None). Overall, having the arguments be as close as possible to what we'd write, mathematically, would be ideal, though I know that it isn't always possible or wise.
