### ISSUE TITLE
Protein alignement notebook

### ISSUE THREAD

**Issue by FarnazH** [theochem/procrustes#31]
@fanwang I couldn't regenerate the protein alignment results you had presented (using https://github.com/theochem/procrustes/blob/master/docs/notebooks/Protein_Structure_Alignment.ipynb). Can you also please take a look at it?
The screenshot below shows the final RMSD I have got (which doesn't match yours) and the error when plotting the transformed coordinates.
![protein_alignment_error](https://user-images.githubusercontent.com/4535622/107471648-42e07b00-6b22-11eb-84b3-803e944574bc.png)

**Comment by fwmeng88** [comment]
I have fixed the problem of `new_C` not defined error with respect to the return object change, 004706a. 
However, I cannot reproduce the rmsd value of 21.72 after structure alignment yet.

**Comment by FarnazH** [comment]
I executed the notebook again using the latest code, and I could regenerate the results you have reported. Thanks.
