### ISSUE TITLE
Update and polish the sphinx docs

### ISSUE THREAD

**Issue by fwmeng88** [theochem/procrustes#54]
This is a reminder for myself that a few things need to be fixed.

- [x] Update the header
- [x] Update contact information using _**QC-Dev community**_
- [x] Update the footnote information in `conf.py`
- [ ] Update the equations and make it consistent with our manuscript.
- [x] Update installation guide
- [x] Update quick start example
- [x] Add API rst file for kopt module
- [ ] fix examples, following . This related to #26
- [x] Update docstrings if necessary: equations, argument names, and default parameters. This relates to #25.
- [x] Add RST file style checker

**Comment by FarnazH** [comment]
@fwmeng88 what do you want to change in the HEADER? There were updated in 06d2c283e58d83a34bb866e4c3638948be328c0d

Also, I am making changes to the docstrings (and equations), and to avoid conflicts, it's best not to change equations now. Then, we should make the paper's appendix consistent with the docstring.

I am also taking care of issue #25, as I messaged you.

**Comment by fwmeng88** [comment]
The HEADER in the [`docs`](https://github.com/theochem/procrustes/tree/master/docs) folder are not updated yet and I will fix it soon following 06d2c28. I will not touch the docstrings and other parts in the PY files for now until you tell me to. 

This is just a reminder for me to double-check before the final release. I will only touch these files located in [`docs`](https://github.com/theochem/procrustes/tree/master/docs), not others. 

Thanks for reminding the potential conflicts I may cause. @FarnazH

**Comment by FarnazH** [comment]
@fwmeng88 can you please add Table 1 and Equation 1 (from the paper) to the documentation (1st page)? We need to make the Procrustes method names clickable so they link to the API documentation. Thanks.

**Comment by fwmeng88** [comment]
I will do it shortly.
